config/routes.rb
Calendar::Application.routes.draw do
  devise_for :users

  resources :events
  resources :calendar

  root :to => "home#index"

  root :to => "calendar#index"
  

end

app/models/event.rb
class Event < ActiveRecord::Base
    
  scope :before, lambda {|end_time| {:conditions => ["ends_at < ?", Event.format_date(end_time)] }}
  scope :after, lambda {|start_time| {:conditions => ["starts_at > ?", Event.format_date(start_time)] }}
  
  # need to override the json view to return what full_calendar is expecting.
  # http://arshaw.com/fullcalendar/docs/event_data/Event_Object/
  def as_json(options = {})
    {
      :id => self.id,
      :name_person => self.name_person,
      :name_professional => self.name_professional,
      :cpf => self.cpf,
      :title => self.title,
      :description => self.description || "",
      :start => starts_at.rfc822,
      :end => ends_at.rfc822,
      :allDay => self.all_day,
      :recurring => false,
      :url => Rails.application.routes.url_helpers.event_path(id)
    }
    
  end
  
  def self.format_date(date_time)
    Time.at(date_time.to_i).to_formatted_s(:db)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  
  # got these tips from
  # http://lyconic.com/blog/2010/08/03/dry-up-your-ajax-code-with-the-jquery-rest-plugin
  before_filter :correct_safari_and_ie_accept_headers
  after_filter :set_xhr_flash

  def set_xhr_flash
    flash.discard if request.xhr?
  end

  def correct_safari_and_ie_accept_headers
    ajax_request_types = ['text/javascript', 'application/json', 'text/xml']
    request.accepts.sort! { |x, y| ajax_request_types.include?(y.to_s) ? 1 : -1 } if request.xhr?
  end
  
  
end

app/controllers/calendar_controller.rb
# calendars are not (yet) a resource in the rails sense of thw word - we
# simply have a url like calendar/index to get the one and only calendar
# this demo serves up.
class CalendarController < ApplicationController
  before_filter :authenticate_user!		
  def index
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.xml

  before_filter :authenticate_user!   

  def index   
    # full_calendar will hit the index method with query parameters
    # 'start' and 'end' in order to filter the results for the
    # appropriate month/week/day.  It should be possiblt to change
    # this to be starts_at and ends_at to match rails conventions.
    # I'll eventually do that to make the demo a little cleaner.
    @events = Event.scoped  
    @events = @events.after(params['start']) if (params['start'])
    @events = @events.before(params['end']) if (params['end'])
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @events }
      format.js  { render :json => @events }
    end
  end

  # GET /events/1
  # GET /events/1.xml
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @event }
      format.js { render :json => @event.to_json }
    end
  end

  # GET /events/new
  # GET /events/new.xml
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.xml
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to(@event, :notice => 'Event was successfully created.') }
        format.xml  { render :xml => @event, :status => :created, :location => @event }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.xml
  # PUT /events/1.js
  # when we drag an event on the calendar (from day to day on the month view, or stretching
  # it on the week or day view), this method will be called to update the values.
  # viv la REST!
  def update
    @event = Event.find(params[:id])
    
    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to(@event, :notice => 'Event was successfully updated.') }
        format.xml  { head :ok }
        format.js { head :ok}
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
        format.js  { render :js => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.xml
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to(events_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
  		if user_signed_in?
    		redirect_to :controller=>'calendar', :action => 'index'
  		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/calendar/index.html.erb
<%= link_to "Novo evento", new_event_path %>

<div id='calendar'></div>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo%><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :Nome_da_pessoa %><br />
    <%= f.text_field :name_person %>
  </div>
  <div class="field">
    <%= f.label :Nome_do_profissional %><br />
    <%= f.text_field :name_professional %>
  </div>
  <div class="field">
    <%= f.label :cpf_ou_nis %><br />
    <%= f.text_field :cpf %>
  </div>
  <div class="field">
    <%= f.label :Horario_inicial %><br />
    <%= f.datetime_select :starts_at %>
  </div>
  <div class="field">
    <%= f.label :Horario_final %><br />
    <%= f.datetime_select :ends_at %>
  </div>
  <div class="field">
    <%= f.label :Dia_todo %><br />
    <%= f.check_box :all_day %>
  </div>
  <div class="field">
    <%= f.label :descrição %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editar eventos</h1>

<%= render 'form' %>

<%= link_to 'Visualizar', @event %> |
<%= link_to 'Voltar', events_path %>

app/views/events/index.html.erb
<h1>Lista de eventos</h1>

<table>
  <tr>
    <th>Titulo</th>
    <th>Nome da pessoa</th>
    <th>Nome do profissional</th>
    <th>Horario inicial</th>
    <th>Horario final</th>
    <th>Dia todo</th>
    <th>Descrição</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @events.each do |event| %>
  <tr>
    <td><%= event.title %></td>
    <td><%= event.name_person %></td>
    <td><%= event.name_professional %></td>
    <td><%= event.starts_at %></td>
    <td><%= event.ends_at %></td>
    <td><%= event.all_day %></td>
    <td><%= event.description %></td>
    <td><%= link_to 'Vizualizar', event %></td>
    <td><%= link_to 'Editar', edit_event_path(event) %></td>
    <td><%= link_to 'Excluir', event, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />
<%= link_to 'Vizualizar calendario', calendar_index_path %>
<br/>
<%= link_to 'Novo evento', new_event_path %>

app/views/events/new.html.erb
<h1>Novo evento</h1>

<%= render 'form' %>

<%= link_to 'Voltar', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Titulo:</b>
  <%= @event.title %>
</p>

<p>
  <b>Nome da pessoa:</b>
  <%= @event.name_person %>
</p>

<p>
  <b>Nome do profissional:</b>
  <%= @event.name_professional%>
</p>

<p>
  <b>Cpf/Nis:</b>
  <%= @event.cpf%>
</p>

<p>
  <b>Horario inicial:</b>
  <%= @event.starts_at %>
</p>

<p>
  <b>Horario final:</b>
  <%= @event.ends_at %>
</p>

<p>
  <b>Dia todo:</b>
  <%= @event.all_day %>
</p>

<p>
  <b>Descrição:</b>
  <%= @event.description %>
</p>


<%= link_to 'Editar', edit_event_path(@event) %> |
<%= link_to 'Voltar', events_path %>

app/views/home/index.html.erb
<h1>Assistencia Social Rolante<h1>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html>
<head>
  <title>Calendar</title>  
  <%= stylesheet_link_tag "fullcalendar.css" %>
  <%= stylesheet_link_tag "application.css" %>
  <%= javascript_include_tag "jquery.js" %>
  <%= javascript_include_tag "jquery.rest.js" %>
  <%= javascript_include_tag "rails.js" %>
  <%= javascript_include_tag "application.js" %>
  
  <!-- these are needed for the calendar. -->
  <%= javascript_include_tag "jquery-ui-1.8.11.custom.min.js" %>
  <%= javascript_include_tag "fullcalendar.js" %>
  <%= javascript_include_tag "calendar.js" %>
  
  <%= csrf_meta_tag %>  
  
  <%= javascript_tag "var AUTH_TOKEN = #{form_authenticity_token.inspect};" if protect_against_forgery? %>
  
</head>
<body>
<div id="user_nav">
  <% if user_signed_in? %>
    Signed in as <%= current_user.email %>. Not you?
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
  <% end %>
</div>
 
<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>
<%= yield %>

</body>
</html>